[package]
name = "iwtsp"
version = "0.1.0"
edition = "2024"

[dependencies]
argmin = "0.10"
argmin-math = { version = "0.4", features = ["nalgebra_latest"] }
nalgebra = "0.32"
reverse = "0.2.2"
statrs = "0.17"

[profile.release]
lto = "fat"
